//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolmatchhistory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lolmatchhistoryEntities : DbContext
    {
        public lolmatchhistoryEntities()
            : base("name=lolmatchhistoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHAMPION> CHAMPIONs { get; set; }
        public DbSet<GAME> GAMEs { get; set; }
        public DbSet<SUMMONER> SUMMONERs { get; set; }
        public DbSet<GAMESTAT> GAMESTATs { get; set; }
        public DbSet<ITEM> ITEMs { get; set; }
        public DbSet<SPELL> SPELLs { get; set; }
    }
}
