//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolmatchhistory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMESTAT
    {
        public long GAMESTAT_ID { get; set; }
        public Nullable<long> GAME_ID { get; set; }
        public Nullable<long> SUMMONER_ID { get; set; }
        public Nullable<int> SUMMONERLEVEL { get; set; }
        public Nullable<long> CHAMPION_ID { get; set; }
        public Nullable<int> CHAMPIONLEVEL { get; set; }
        public Nullable<long> SPELL1_ID { get; set; }
        public Nullable<long> SPELL2_ID { get; set; }
        public Nullable<long> TEAM_ID { get; set; }
        public Nullable<sbyte> WIN { get; set; }
        public Nullable<System.TimeSpan> TIMEPLAYED { get; set; }
        public Nullable<int> CHAMPIONSKILLED { get; set; }
        public Nullable<int> NUMDEATHS { get; set; }
        public Nullable<int> ASSISTS { get; set; }
        public Nullable<int> KILLINGSPREES { get; set; }
        public Nullable<int> LARGESTKILLINGSPREE { get; set; }
        public Nullable<int> LARGESTMULTIKILL { get; set; }
        public Nullable<int> FIRSTBLOOD { get; set; }
        public Nullable<int> DOUBLEKILLS { get; set; }
        public Nullable<int> TRIPLEKILLS { get; set; }
        public Nullable<int> QUADRAKILLS { get; set; }
        public Nullable<int> PENTAKILLS { get; set; }
        public Nullable<int> UNREALKILLS { get; set; }
        public Nullable<int> TURRETSKILLED { get; set; }
        public Nullable<int> BARRACKSKILLED { get; set; }
        public Nullable<sbyte> NEXUSKILLED { get; set; }
        public Nullable<int> GOLD { get; set; }
        public Nullable<int> GOLDEARNED { get; set; }
        public Nullable<int> GOLDSPENT { get; set; }
        public Nullable<int> ITEMSPURCHASED { get; set; }
        public Nullable<int> NUMITEMSBOUGHT { get; set; }
        public Nullable<int> CONSUMABLESPURCHASED { get; set; }
        public Nullable<int> ITEM0 { get; set; }
        public Nullable<int> ITEM1 { get; set; }
        public Nullable<int> ITEM2 { get; set; }
        public Nullable<int> ITEM3 { get; set; }
        public Nullable<int> ITEM4 { get; set; }
        public Nullable<int> ITEM5 { get; set; }
        public Nullable<int> ITEM6 { get; set; }
        public Nullable<int> LEGENDARYITEMSCREATED { get; set; }
        public Nullable<int> TOTALDAMAGEDEALT { get; set; }
        public Nullable<int> TOTALDAMAGEDEALTTOCHAMPIONS { get; set; }
        public Nullable<int> DAMAGEDEALTPLAYER { get; set; }
        public Nullable<int> PHYSICALDAMAGEDEALTPLAYER { get; set; }
        public Nullable<int> PHYSICALDAMAGEDEALTTOCHAMPIONS { get; set; }
        public Nullable<int> LARGESTCRITICALSTRIKE { get; set; }
        public Nullable<int> MAGICDAMAGEDEALTPLAYER { get; set; }
        public Nullable<int> MAGICDAMAGEDEALTTOCHAMPIONS { get; set; }
        public Nullable<int> TRUEDAMAGEDEALTPLAYER { get; set; }
        public Nullable<int> TRUEDAMAGEDEALTTOCHAMPIONS { get; set; }
        public Nullable<int> TOTALDAMAGETAKEN { get; set; }
        public Nullable<int> PHYSICALDAMAGETAKEN { get; set; }
        public Nullable<int> MAGICDAMAGETAKEN { get; set; }
        public Nullable<int> TRUEDAMAGETAKEN { get; set; }
        public Nullable<int> TOTALHEAL { get; set; }
        public Nullable<int> TOTALUNITSHEALED { get; set; }
        public Nullable<System.TimeSpan> TOTALTIMECROWDCONTROLDEALT { get; set; }
        public Nullable<int> MINIONSDENIED { get; set; }
        public Nullable<int> MINIONSKILLED { get; set; }
        public Nullable<int> NEUTRALMINIONSKILLED { get; set; }
        public Nullable<int> NEUTRALMINIONSKILLEDYOURJUNGLE { get; set; }
        public Nullable<int> NEUTRALMINIONSKILLEDENEMYJUNGLE { get; set; }
        public Nullable<int> SUPERMONSTERKILLED { get; set; }
        public Nullable<int> SIGHTWARDSBOUGHT { get; set; }
        public Nullable<int> VISIONWARDSBOUGHT { get; set; }
        public Nullable<int> WARDPLACED { get; set; }
        public Nullable<int> WARDKILLED { get; set; }
        public Nullable<int> IPEARNED { get; set; }
    }
}
