//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolmatchhistory
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME
    {
        public long GAME_ID { get; set; }
        public Nullable<System.DateTime> GAMEDATE { get; set; }
        public string MAPTYPE { get; set; }
        public string GAMEMODE { get; set; }
        public string GAMESUBTYPE { get; set; }
        public Nullable<int> IPEARNED { get; set; }
        public Nullable<sbyte> INVALID { get; set; }
        public Nullable<System.DateTime> CREATIONDATE { get; set; }
        public string CREATIONUSER { get; set; }
    }
}
