//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolmatchhistory
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int ITEM_ID { get; set; }
        public string ITEMNAME { get; set; }
    }
}
