//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lolmatchhistory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUMMONER
    {
        public long SUMMONER_ID { get; set; }
        public string SUMMONERNAME { get; set; }
        public Nullable<int> PROFILEICON_ID { get; set; }
        public Nullable<System.DateTime> REVISIONDATE { get; set; }
        public Nullable<short> LEVEL { get; set; }
    }
}
